cap config values to ensure they fit into a varint
We need to ensure we cap various values that are passed via u64 as we need to be able to encude these via varint encoding. 

If we fail to cap these we will crash quiche when using a too big value:

```
thread '<unnamed>' panicked at octets/src/lib.rs:691:9:
internal error: entered unreachable code
stack backtrace:
   0:        0x1420af66c - <unknown>
   1:        0x1420ee99c - <unknown>
   2:        0x1420a581c - <unknown>
   3:        0x1420af520 - <unknown>
   4:        0x1420b1810 - <unknown>
   5:        0x1420b164c - <unknown>
   6:        0x1420b23d8 - <unknown>
   7:        0x1420b1f7c - <unknown>
   8:        0x1420afb20 - <unknown>
   9:        0x1420b1c5c - <unknown>
  10:        0x14210c9e8 - <unknown>
  11:        0x14210ca58 - <unknown>
  12:        0x142027734 - <unknown>
  13:        0x141f84c88 - <unknown>
  14:        0x141f711cc - <unknown>
  15:        0x141fb755c - <unknown>
  16:        0x141e31904 - <unknown>
fatal runtime error: failed to initiate panic, error 5
```